### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by oneEyedSunday** [Drawaes/TrimDB#32]
Hello @gra-moore I am trying to familiarize myself with this project.
I am reading the suggested LSM tree paper.

I tried to run the tests today, after cloning the repo. But I run into the following error on an osx system

```
dotnet test
Test run for /Users/ispoa/Projects/TrimDB/artifacts/tests/TrimDB.Core.Facts.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.DllNotFoundException: Unable to load shared library 'Kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libKernel32.dll, 1): image not found
   at TrimDB.Core.Interop.Windows.Memory.VirtualFree(IntPtr lpAddress, UIntPtr dwSize, FreeType dwFreeType)
   at TrimDB.Core.InMemory.SkipList64.NativeAllocator64.Dispose(Boolean isDisposing) in /_/src/TrimDB.Core/InMemory/SkipList64/NativeAllocator64.cs:line 89
   at TrimDB.Core.InMemory.SkipList64.SkipListAllocator64.Finalize() in /_/src/TrimDB.Core/InMemory/SkipList64/SkipListAllocator64.cs:line 51


Test Run Aborted.

```

My dotnet version
```
dotnet --version
3.1.200
```

```
uname -v
Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
```

I can run the benchmarks in `Release` configuration, unfortunately, cannot find a way to run the tests.
All help appreciated.

cc @vchirikov

**Comment by oneEyedSunday** [comment]
Update.

Is this windows [only](https://stackoverflow.com/a/56275239/5134605)? 
[Seems so](https://stackoverflow.com/a/47882980/5134605)

```
the .NET Core version is Windows only: ".NET Core version - Windows only" and "Note 2: The .NET Core version is for .NET Core 2.0 or above through .NET Standard 2.0. Currently, it requires a Windows system to run. It does not work on Linux or Mac or Xamarin."
```
